stages:
  - build_docker_image
  - build
  - deploy

services:
  - docker:dind
before_script:
  - eval $(ssh-agent -s)
  # Подгружаем ключ. После этого, можем подключаться ssh из оперативки.
  - ssh-add <(echo $ANSIBLE_ansible_ssh_key |base64 --decode)
  # Очищаем переменную.
  - printenv
  - unset ANSIBLE_ansible_ssh_key
  # Посмотреть список загруженных ключей.
  - ssh-add -l
  - printenv
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker:image_build:
  stage: build_docker_image
  image: docker:stable
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_BUILD_REF --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:latest


build_docs:
  stage: build
  image: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  script:
    - pwd
    - ls
    - bundle exec middleman build
  artifacts:
    paths:
      - build
    expire_in: 1 week

deploy_docs:
  stage: deploy
  image: registry.gitlab.com/instamart-ci/ansible:429a64f0f089e6fcd0432a9b9eb000376883ea37
  dependencies:
    - build_docs
  script:
    - ls  -la


